"""
config.py – Central configuration for CultureLens.

All tuneable thresholds, paths and constants live here so they are
easy to find, adjust during a demo, and explain in a viva.
"""

from pathlib import Path

# ── Project paths (relative to repo root) ──────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
FRONTEND_DIR = PROJECT_ROOT / "frontend"

PHRASES_PATH = DATA_DIR / "phrases.json"
CULTURES_PATH = DATA_DIR / "cultures.json"
TRAINING_DATA_PATH = DATA_DIR / "training_data.csv"
EVAL_SET_PATH = DATA_DIR / "eval_set.json"
CLASSIFIER_PATH = MODELS_DIR / "classifier.joblib"
PHRASE_EMBEDDINGS_PATH = MODELS_DIR / "phrase_embeddings.npy"

# ── Input validation ───────────────────────────────────────────────
MAX_INPUT_LENGTH = 5000          # characters
MIN_INPUT_LENGTH = 1             # reject empty strings

# ── Layer 1: Rule-based detector ───────────────────────────────────
RULE_CONFIDENCE = 0.95           # rules are high-confidence by design

# ── Layer 2: Semantic detector ─────────────────────────────────────
SEMANTIC_THRESHOLD = 0.62        # cosine-sim cutoff for flagging
SEMANTIC_MODEL_NAME = "all-MiniLM-L6-v2"  # ~80 MB, CPU-friendly
MAX_CHUNKS_PER_SENTENCE = 40     # upper bound on n-gram candidates
SEMANTIC_NGRAM_MIN = 3           # minimum tokens in a chunk
SEMANTIC_NGRAM_MAX = 6           # maximum tokens in a chunk

# ── Layer 3: ML classifier ────────────────────────────────────────
ML_CONFIDENCE_THRESHOLD = 0.60   # min predicted probability to flag
ML_RANDOM_SEED = 42              # reproducibility

# ── Tone analyzer ─────────────────────────────────────────────────
TONE_MISMATCH_THRESHOLD = 0.35   # difference to trigger a tone flag

# ── Scorer ─────────────────────────────────────────────────────────
# score = min(100, 100 * (1 - exp(-k * Σ(sev_i * conf_i / √N))))
SCORER_K = 0.25                  # scaling constant

# Severity cut-offs for adjusted_risk → severity level
SEVERITY_LOW_MAX = 1.5           # adjusted_risk ≤ this → severity 1
SEVERITY_MED_MAX = 2.5           # adjusted_risk ≤ this → severity 2
                                  # above → severity 3

# ── Score labels ───────────────────────────────────────────────────
SCORE_LABELS = [
    (24, "Low"),
    (49, "Moderate"),
    (74, "High"),
    (100, "Very High"),
]

# ── API / Server ───────────────────────────────────────────────────
APP_VERSION = "1.0.0"
APP_TITLE = "CultureLens"
APP_DESCRIPTION = "Cross-Cultural Communication Advisor"

# ── Valid categories (used for validation) ─────────────────────────
VALID_CATEGORIES = frozenset([
    "idiom",
    "slang",
    "sports_metaphor",
    "military_metaphor",
    "corporate_jargon",
    "vague_time",
    "date_format",
    "units_numbers",
    "indirect_refusal",
    "hedging",
    "blunt_feedback",
    "sarcasm_humor",
    "politeness_formula",
    "cultural_reference",
    "phrasal_verb",
    "tone_mismatch",       # generated by tone analyzer
    "sentence_level",      # generated by ML classifier
])
